# Generated by Django 5.1.1 on 2024-09-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryen',
            options={'verbose_name': 'CategoryEn', 'verbose_name_plural': 'CategoryEn'},
        ),
        migrations.AlterModelOptions(
            name='newsen',
            options={'verbose_name': 'NewsEn', 'verbose_name_plural': 'NewsEn'},
        ),
        migrations.AlterField(
            model_name='newsen',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='mars_news.categoryen'),
        ),
    ]
